# Generated by Django 6.0.3 on 2026-06-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_quantity_sold', models.IntegerField()),
                ('absolute_error', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentage_error', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bias', models.IntegerField()),
                ('status', models.CharField(choices=[('ACCURATE', 'Accurate'), ('OVER_FORECASTED', 'Over Forecasted (Risk of Overstock)'), ('UNDER_FORECASTED', 'Under Forecasted (Risk of Stockout)')], default='ACCURATE', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
