# Generated by Django 6.0.3 on 2026-06-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationmetric',
            name='forecast_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.forecastresult'),
        ),
    ]
