# Generated by Django 6.0.3 on 2026-06-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_of_stock_left', models.IntegerField()),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('OVERSTOCK', 'Overstock'), ('STOCKOUT_RISK', 'STOCKOUT_RISK')], default='OK', max_length=20)),
                ('recommended_reorder_quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
