# Generated by Django 6.0.3 on 2026-06-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_quantity', models.IntegerField()),
                ('horizon', models.IntegerField(choices=[(7, '7 DAYS'), (30, '30 DAYS')])),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=7)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['product'], name='forecasting_product_e6ddcb_idx'), models.Index(fields=['product', '-generated_at'], name='forecasting_product_297b10_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('predicted_quantity__gte', 0)), name='forecast_result_predicted_quantity_gte_0')],
            },
        ),
    ]
