# Generated by Django 6.0.3 on 2026-06-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_changed', models.IntegerField()),
                ('reason', models.CharField(choices=[('SALE', 'Customer Purchase'), ('RESTOCK', 'Supplier Delivery'), ('WASTE', 'Damaged / Expired Goods'), ('CORRECTION', 'Manual Inventory Count Audit')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', '-created_at'], name='products_st_product_136c7e_idx')],
            },
        ),
    ]
